### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by kruzaavn** [kruzaavn/JTF-191-Application#117]
We're giving out awards now post cruise. Display on Aviator profile.

**Comment by kruzaavn** [comment]
Screamer submitted these for award ![](https://cdn.discordapp.com/attachments/828980379482325052/913323689443995679/Salamis_Ribbons_191st.jpg)

vectorize

**Comment by afuggetta** [comment]
@kruzaavn I have looked into this and prototyped something, see below.

I have added an "Award" model, where you can add a name, URL to the image, and priority for the sorting:
![image](https://user-images.githubusercontent.com/5176293/144366496-97330819-e02f-4a89-bbac-2270b8425a4e.png)

In each Aviator's profile, you can then select multiple awards:
![image](https://user-images.githubusercontent.com/5176293/144366555-10f24014-7022-4889-95f9-c572d905b9f9.png)

And it currently shows like this:
![image](https://user-images.githubusercontent.com/5176293/144366592-00a49d99-9c71-4ec0-a236-fcac12750d42.png)


Two outstanding items/thoughts:
- Should we upload images from the admin, or reference outside ones as it is now? (Maybe a blob storage file?)
- I need to figure out how to reverse the front-end and show the odd ones on top as it should

let me know what you think.

**Comment by kruzaavn** [comment]
@afuggetta Something to consider, it could be possible earn an award multiple times.

so i'd suggest something like this, 

 award ---> citation <--- aviator

and use the citation to capture unique awards

----

we've already got blob storage setup in production, so once an image gets uploaded it's put into our azure blob storage so i'd suggest using the image file field instead of a url.

**Comment by afuggetta** [comment]
> 

Yes, I was thinking of that as well actually. I'll look into your suggestion.

I have fixed the layout, I believe:
![image](https://user-images.githubusercontent.com/5176293/144459286-906d3e1b-0ba8-4dfa-830c-58640e376ad4.png)


---
Great, I'll change the image from URL to the file field

**Comment by kruzaavn** [comment]
> Screamer submitted these for award ![](https://camo.githubusercontent.com/7ae9a1b0747a3a43049b9bb4cb1e41838ca3c0e6aed8e59145b4760c47cc1234/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3832383938303337393438323332353035322f3931333332333638393434333939353637392f53616c616d69735f526962626f6e735f31393173742e6a7067)
> 
> vectorize to remove JPEG interference distortions

vectorized ribbons [here](https://drive.google.com/drive/folders/15naa6T6br6a8AfCJN0YlDJsBbm_IQKNB?usp=sharing) I had to edit some of the designs in order mutate them more drastically since a couple were small edits on real awards. Also removed the icons since they are too rough to show up well.
