### ISSUE TITLE
Update design to allow a personal page

### ISSUE THREAD

**Issue by kruzaavn** [kruzaavn/JTF-191-Application#125]
We've wanted to implement a personal page for each aviator in the wing. It makes sense on a lot of levels to do this. What the design and functionality of this page should be needs to be scoped and implemented.

**Comment by afuggetta** [comment]
@kruzaavn finally found some time to add the LOA as discussed to the personal page:

![image](https://user-images.githubusercontent.com/5176293/145871725-a851fed5-7bfa-48a8-a14f-6206e5983974.png)

you can delete each:
![image](https://user-images.githubusercontent.com/5176293/145871764-e552c114-7651-404e-b82f-620baf1d3190.png)

or add a new one:
![image](https://user-images.githubusercontent.com/5176293/145871835-5504e04d-7a35-4fe3-a2d3-1f583f988695.png)

**Comment by afuggetta** [comment]
As agreed, added the LOA to the event:
![image](https://user-images.githubusercontent.com/5176293/146086092-b8ac03c4-4c8f-47b3-9fd8-d811cf65b181.png)

also default event name, squadron and aviator on submit, so I am hiding those fields when LOA is selected:
![image](https://user-images.githubusercontent.com/5176293/146086187-6cf23c43-48c3-4542-a533-9db5ba9f66e3.png)
