### ISSUE TITLE
Dynamic Liveries

### ISSUE THREAD

**Issue by kruzaavn** [kruzaavn/JTF-191-Application#129]
Ok I'm serous now, we now have time and people to tackle dynamic livery generation. 

The goal is to take in a template squadron livery and dynamically create a unique livery for each squadron member in order to reduce the work and file size requirements to generate the full livery package and create a base for livery makers. 

we need to define what parameters we will support
  - color bird variants for XO/CO?
  - name & callsign
  - kills?

See [this arigoons](https://www.airgoons.com/w/How_To_Make_A_DCS_Livery) article for some inference in how the system works. **beware this isn't a complete guide**

see [this ed forum](https://forums.eagle.ru/topic/112480-explanation-for-descriptionlua/?do=findComment&comment=4144890) post alludes to the how a livery gets interpreted at run and could allow us to cross reference many files shrinking the package.

**Comment by afuggetta** [comment]
@kruzaavn @tonyhen I think I have a working solution for this.

There are three main pieces in this:
1- Livery skins: this is where you get to customize a specific part of a livery DDS file and add text.
![image](https://user-images.githubusercontent.com/5176293/146651351-99c2e644-7e1e-402f-a7a4-758da1f44928.png)
Here you pass a base DDS file URL and a JSON component. In the JSON you have an array of objects.
Each object has a series of options to customize the text (see picture above) A new DDS file will be created and uploaded in the correct directory for each aviator from this.

2- Livery lua sections: This is where it got interesting as there is no easy way to build a LUA file without knowing exactly what each piece does. So instead, I thought to leave it to the livery creator to add each section.
![image](https://user-images.githubusercontent.com/5176293/146651413-dacbb3cd-e202-4f5d-b65b-958ef7ce2097.png)
Pretty much you will end up with a bunch of these sections (or one if you would like...) that will be linked to the main Lua.
While this is not as clean as I would like, it is flexible enough and I think a good start.

3- Liveries: This is all comes together:
![image](https://user-images.githubusercontent.com/5176293/146651473-80c8c15e-43ea-455d-aae2-9ef8a11ab06a.png)
You create a livery selecting a squadron and an airframe. I added a position code, so this is how you can differentiate which livery is for a CO, XO, OPSO, or BASE. The system will know how to interpret this and will automatically pull only the livery that is associated with each aviator's role (i.e. if I am an XO, it will pull the XO livery information if there is one).

After this runs, which is set up as an API, it uploads everything to an Azure storage account BLOB structure.
A separate API, accessible from the profile page of each aviator will pull this down as a downloadable file so it can be saved into the local DCS folder.

What are your thoughts?

**Comment by kruzaavn** [comment]
So far so good, 

A couple of quibbles, 

1. Squadrons already have an airframe foreign key so for the last step you don't need to store the airframe. 
1.  On the Skin model you have URL field to reference the actual dds file, would we not want to make this a file field to support uploading files into the system?
1. For the description model do we intend to have one lua template for the whole Livery Template or is it going to be one for one with the Skin?

When you get a second can you push and make a pull request for this.

**Comment by afuggetta** [comment]
- Removed the aiframe from the livery section as pointed out
- Changed the URL to a file field
- Added a validation against a json schema for the description
- The description is on for one with the skin at the moment. so you can have smaller complexity

Added the front end to the profile page:

https://user-images.githubusercontent.com/5176293/146791415-7bbb198d-701f-40bd-8210-88861469af2d.mp4

A small video on profile usage. The second paragraph and button only show up for admins.
