### ISSUE TITLE
Document Area

### ISSUE THREAD

**Issue by SciNemo** [kruzaavn/JTF-191-Application#136]
We need a place on the website where JTF doctrine, SOP, documents, etc can be viewed by members. It could be a simple as a duplication of the training qualifications area, just renamed to fit the purpose.

**Comment by kruzaavn** [comment]
This is the next item we've got to tackle. Ideally if this is going to be more or less a reuse of the training documentation we should generalize the infrastructure.

**Comment by SciNemo** [comment]
It would be nice to add some functionality to define the sorting of the documentation sections and entries. Currently it just goes top to bottom based on the order the entries are added in, which requires too much forethought for I.

**Comment by SciNemo** [comment]
Via a multi-digit index or an alphanumeric index would be preferable as it would save us from having to cluttered document names with something appended to the front to achieve a desired order.

**Comment by kruzaavn** [comment]
Ok easy enough.

**Comment by kruzaavn** [comment]
Document area complete, need to implement updates to vuetify in order to deploy
