### ISSUE TITLE
Nil value in StatsPlugin.lua

### ISSUE THREAD

**Issue by SverreTolboe** [kruzaavn/JTF-191-Application#144]
Hi AMB here.
I get this error on my server when running a mission. Server started, but no one is logged in yet.
It seems that the statsPlugin is missing users. Maby a solution could be to check for nil value before running function?

```
2022-02-04 11:57:01.367 ERROR   SCRIPTING: Mission script error: [string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:85: attempt to index field 'initiator' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:85: in function 'common'
	[string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:113: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

```

**Comment by kruzaavn** [comment]
@SverreTolboe every event generated with a user needs to have an initiator, this is failing according to line 85

```lua
event.unit = _event.initiator:getDesc()
```

the point of this method is getting the data about which aircraft/ship/whatever fired the event. So this should always have a value and failing before we even check to see if someone is controlling the unit. Are you doing something "Strange" like destroying units through a script call?

**Comment by SverreTolboe** [comment]
No iam not destroying anything thru the script. Only thing i have is MOOSE AI scripts that attacks other units. In my mission script iam using MOOSE Framework,  CTLD and CSAR scripts. The 2 last one is not modified.

**Comment by kruzaavn** [comment]
I suspect it's the mission without other data, the other servers are working and that's the first degree of freedom i want to sort out. 

Yout original point is not invalid, but i'm still scratching my head that it's an edge case that we'd have to cover. If you don't mind sharing the mission so i can investigate a bit more? 

Aso can you share with me a copy of your full logs file that only has this single mission run on it so it's easier to filter.

**Comment by kruzaavn** [comment]
you can drag and drop these files in the chat

**Comment by SverreTolboe** [comment]
[Caucasus_Conflict.zip](https://github.com/kruzaavn/JTF-191-Application/files/8004623/Caucasus_Conflict.zip)
Here you go :)
[dcs-AMB.log](https://github.com/kruzaavn/JTF-191-Application/files/8004640/dcs-AMB.log)

Might be some more issues after update of DCS client today

**Comment by kruzaavn** [comment]
can you verify that you [desanitized](https://github.com/kruzaavn/JTF-191-Application/tree/master/lua_scripts/server/hooks) the `MissionScripting.lua` file?

**Comment by SverreTolboe** [comment]
I needed to do it again since the update. Now there most of the errors are gone from last log file. 
It seems that the initial error went away after the update of the DCS server. Will report back if i see it again.
@kruzaavn  thank you for looking into this

**Comment by SverreTolboe** [comment]
Still get that error, and it seems like it is comming when a AI get killed.
```
2022-02-05 14:40:12.228 ERROR   SCRIPTING: Mission script error: [string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:85: attempt to index field 'initiator' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:85: in function 'common'
	[string "C:\Users\sverre.tolboe\Saved Games\DCS.openbeta_server\\Scripts\Hooks\ServerManagement\Load\StatsPlugin.lua"]:113: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

```

Here is the log file:
[dcs-Amb2.log](https://github.com/kruzaavn/JTF-191-Application/files/8008209/dcs-Amb2.log)

**Comment by kruzaavn** [comment]
Good news and bad news

Good news is that there is nothing wrong with the stats plugin, at least for me, as well as this is a noisy fail through. Which means even though you're logging an error it's just logging it and continuing to function.

Bad News there isn't anything i can do about this error. This is the raw event that triggers everything

```
2022-02-05 14:44:47.796 INFO    SCRIPTING: Raw DCS Event: {"time":340.037,"target":{"id_":16914433},"weapon":{"id_":16851713},"id":28,"weapon_name":"UH-60A"}
```

my guess is that somewhere along the line ED missed some special logic for the UH-60A to correctly generate the event it looks like the initiator and weapon are being swapped.
