### ISSUE TITLE
Instructor role

### ISSUE THREAD

**Issue by SciNemo** [kruzaavn/JTF-191-Application#48]
A role for JTF-191 instructors that grants perms to add events to the website calendar.

**Comment by kruzaavn** [comment]
So currently everyone has the capability to add and modify events do you want a special event category for IP training?

**Comment by SciNemo** [comment]
I was not aware every user could add and modify events. In that case, yes a special event category for indoc training would be appreciated to make it easier for trainees to spot them on the calendar.
