### ISSUE TITLE
Add Discord ID example to application (Payno#8263)

### ISSUE THREAD

**Issue by Smallstheamish** [kruzaavn/JTF-191-Application#54]
For incoming applicants, I would like to specify the proper Discord syntax in the app so that we are able to reach out to applicants on other mediums, as some don't check email.
Many don't include the (#xxxx) on their name, which makes them impossible to track down
Example: Payno#8263

**Comment by kruzaavn** [comment]
Reopening issue, this needs to be done. We can probably just add form checking to the recruitment page to make sure the fully qualified discord tag is entered.
