### ISSUE TITLE
Army wants warrants?

### ISSUE THREAD

**Issue by kruzaavn** [kruzaavn/JTF-191-Application#58]
the boys in green want to roleplay warrant's, who am I to say they can't. This requires extending the database model for the rank code interface and rendering in the UI.

While we do this we may want to investigate extensibility to other organizations such as coalition squadrons, I for one would like to be an Air Commodore when the Eurofighter comes out. I don't know if the current framework needs to become user data driven but that's one option.

**Comment by Toasterj** [comment]
fix for now is in for the army ranks. I will rework it to include other coalition forces.

**Comment by kruzaavn** [comment]
warrants are in issue closed
