### ISSUE TITLE
New User Registration Errors

### ISSUE THREAD

**Issue by Smallstheamish** [kruzaavn/JTF-191-Application#69]
Two errors have occured with every new registered user:
1. The most prevalent, the registree is notified that the "username has already been assigned to a user"
2. Upon submission, the form is replaced with several blank boxes and exclamation points
![image](https://user-images.githubusercontent.com/58446240/119416240-d6485100-bcb8-11eb-826b-93f963b83dd8.png)

**Comment by kruzaavn** [comment]
this issue has been resolved
