### ISSUE TITLE
Application changes for Rotary Ops

### ISSUE THREAD

**Issue by Smallstheamish** [kruzaavn/JTF-191-Application#75]
Two step issue:

1. Consider changing the preferred airframe from "Huey" to "Helicopter", "Rotary", something of the like.
2. Add Hind, KA50, in the future add Apache, Kiowa, etc. to "Owned modules" section

Since rotary ops are in big dev mode in DCS and internally we swap between airframes, this would allow a more general option, with specific owned airframes to be attached to said aviator.

**Comment by kruzaavn** [comment]
where do you want to make this change?

**Comment by Smallstheamish** [comment]
On the front end application for new aviators. Makes it apparent that the rotary ops are in no way limited to the Huey and that we are dynamic to the metttc

**Comment by kruzaavn** [comment]
you can do that already by adding another dcs module to the database

**Comment by kruzaavn** [comment]
<img width="1130" alt="Screen Shot 2021-06-18 at 7 06 30 PM" src="https://user-images.githubusercontent.com/7274055/122622979-7602c000-d068-11eb-9bf0-e8126120ab77.png">

**Comment by Smallstheamish** [comment]
Issue resolved internally via above ^
